http_port 3128
acl localnet src 127.0.0.1/32 ::1
http_access allow localnet
http_access deny all
cache_dir ufs /var/spool/squid 1000 16 256
maximum_object_size 100 MB
maximum_object_size_in_memory 10 MB
refresh_pattern -i \.(gif|png|jpg|jpeg|ico|svg|css|js|woff|woff2|ttf|json)$ 14400 80% 43200 override-expire refresh-ims
refresh_pattern . 0 20% 43200
