#!/usr/bin/python3
"""Generate Bash installer translations for Debian systems without Python yet."""
import json
from pathlib import Path
import re
import shlex
import sys

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / 'assets/i18n/en.json').read_text(encoding='utf-8'))
messages = set()
for path in [ROOT / 'install.sh', *(ROOT / 'installer').glob('*.sh'), ROOT / 'iso/setup-after-install.sh']:
    if path.name == 'english.sh':
        continue
    source = path.read_text(encoding='utf-8')
    for match in re.finditer(r'paimenos_text\s+(?=[\x27\"])', source):
        lexer = shlex.shlex(source[match.end():], posix=True, punctuation_chars='()')
        lexer.whitespace_split = True
        message = lexer.get_token()
        if message not in catalog:
            raise ValueError('Missing installer translation: ' + message)
        messages.add(message)
output = '#!/bin/bash\n# Generated by tools/build-shell-translations.py from assets/i18n/en.json.\n'
output += 'declare -A PAIMENOS_ENGLISH=(\n'
for message in sorted(messages):
    output += '    [' + shlex.quote(message) + ']=' + shlex.quote(catalog[message]) + '\n'
output += ')\n'
target = ROOT / 'installer/english.sh'
if sys.argv[1:] == ['--check']:
    if not target.is_file() or target.read_text(encoding='utf-8') != output:
        raise SystemExit('Run python3 tools/build-shell-translations.py')
else:
    target.write_text(output, encoding='utf-8')
